### ISSUE TITLE
doesn't build

### ISSUE THREAD

**Issue by bkerin** [agvxov/csope#1]
I don't know if it's something in my setup or what but it's the old can't-find-main thing, I just don't recall what I did about it last time I saw it.  About all the C stuff I build is autoconf these days 

```
$ make
Package history was not found in the pkg-config search path.
Perhaps you should add the directory containing `history.pc'
to the PKG_CONFIG_PATH environment variable
No package 'history' found
gcc source/lookup.h -o object/lookup.h.gch
gcc source/constants.h -o object/constants.h.gch
gcc source/keys.h -o object/keys.h.gch
gcc source/invlib.h -o object/invlib.h.gch
gcc source/library.h -o object/library.h.gch
gcc source/vp.h -o object/vp.h.gch
gcc source/global.h -o object/global.h.gch
gcc source/egrep.h -o object/egrep.h.gch
gcc source/build.h -o object/build.h.gch
gcc source/scanner.h -o object/scanner.h.gch
gcc config/colors.h -o object/colors.h.gch
gcc  -O3 -flto=auto -fomit-frame-pointer -I config/ -I    -c source/command.c -o object/command.o
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [Makefile:40: object/command.o] Error 1
```

**Comment by agvxov** [comment]
> No package 'history' found

seems like you are missing the GNU Readline headers and therefor pkg-config (--cflags) fails to expand to something functional.
as a reference, this is how that last command looks on my system:
```
gcc  -O3 -flto=auto -fomit-frame-pointer -I config/ -I  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -c source/command.c -o object/command.o
```
you should install `readline` through your distros package manager; or if its already installed, then the automatic system configuration of pkg-config must have went wrong somehow.

**Comment by jmdevin** [comment]
I had the same error as @bkerin on Ubuntu 24.04. I have the `history.h` file at `/usr/include/readline/history.h`, so it's not missing, it's just not being found. I deleted the word 'history' from the first line of the Makefile and `make` ran without errors (with a few warnings, but I believe they were already present). The resulting binary seems to work correctly.

I do have both the `libreadline-dev` and `readline-common` apt packages installed, so I'm not sure which one the `history.h` file belongs to.

**Comment by agvxov** [comment]
@jmdevin
Thanks for providing the OS, I was able to look into it:

libreadline and libhistory are documented as 2 independent libraries, however they are conventionally shipped together, because the proper readline experience requires using history functionality.

What this produces -on for example on Gentoo- are the appropriate headers (`readline/*.h`), the shared libraries (libreadline.so and libhistory.so), and the pkg-config library files (readline.pc and history.pc).

On the other hand, Ubuntu only ships the readline library and .pc.
Why? because libreadline apparently contains duplicate symbols for history functionality.
Meaning, that libhistory is technically obsolete.
There's actually a small note about this in the documentation...

So the problem is a combination of GNU creating footguns, Ubuntu pulling the trigger and me not being there to witness the shot.

As you mentioned, just removing libhistory as a dependency should fix it, globally too.

@bkerin
Sorry for the inconvenience.

**Comment by agvxov** [comment]
[6180bff](https://github.com/agvxov/csope/commit/6180bff2439c588f8387ac189b2b4140a5fa7998) fixes this

**Comment by jmdevin** [comment]
Thanks for the quick fix
